databaseChangeLog:
  - changeSet:
      id: db.changelog-2020-07-16--add-setup-product-source-sites-setup-data-1
      author: 0lezhka
      context: production, develop
      changes:
        - loadData:
            columns:
              - column:
                  name: application_message_id
                  type: numeric
              - column:
                  name: application_message
                  type: string
            commentLineStartsWith: "#"
            encoding: UTF-8
            file: /db/changelog/v-1.0/setupDataFiles/setup_application_messages.csv
            quotchar:  ''''
            relativeToChangelogFile: false
            separator: ';'
            tableName: setup_application_messages
            usePreparedStatements: true
